sudo: required
services:
    - docker

before_install:
    - docker build -t stevejohansson/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true stevejohansson/react-test npm test

after_success:
    - docker build -t stevejohansson/multi-client ./client
    - docker build -t stevejohansson/multi-nginx ./nginx
    - docker build -t stevejohansson/multi-server ./server
    - docker build -t stevejohansson/multi-worker ./worker
# Log in to the docker CLI
    - "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push them to docker hub
- docker push stevejohansson/multi-client
- docker push stevejohansson/multi-nginx
- docker push stevejohansson/multi-server
- docker push stevejohansson/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-central-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-central-1-873116259517
    bucket_path: docker-multi
    on:
        branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
